# Generated by Django 3.2.5 on 2021-09-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderproduct'),
        ('orders', '0003_alter_payment_payment_id'),
    ]

    operations = [
    ]
